### ISSUE TITLE
get images always returns png

### ISSUE THREAD

**Issue by panjea** [Amatobahn/FigmaPy#21]
my code is requesting SVG, but i am getting PNG back, am i doing something wrong, or has their API changed?

```python
	ires = fig.get_file_images(
		file_key=file_key, ids=ids,
		scale=1, format='svg',
	)
	print(ires.images)
	html = []
	for id in ires.images:
		url = ires.images[ id ]
		ireq = requests.get(url)
		a,b = id.split(':')
		print(ireq.content)
		ext = 'svg'
		if ireq.content.startswith(b'\x89PNG'):
			ext = 'png'   ## OH NO!

```

**Comment by hannesdelbeke** [comment]
Hi, will follow up on this. In the meantime try us the func get_vector_images instead of getfileimages.

Can you share code on how you setup the fig var too?

**Comment by panjea** [comment]
i just tried `get_vector_images` but i'm still getting PNG files back.
My figma doc has just two rectangles, and some text.  Here is how i construct `fig`

```
	fig = figmapy.FigmaPy(token=my_token)
	file = fig.get_file(key=file_key)
	page1 = file.document.children[0]
```

then i pass the children from page1 to fig.get_vector_images

**Comment by hannesdelbeke** [comment]
fixed in https://github.com/Amatobahn/FigmaPy/commit/437128eb7b195c3d167910beeab4ef3a6338313d

**Comment by hannesdelbeke** [comment]
tested with your sample code and now returns SVG

**Comment by panjea** [comment]
confirmed fixed. Thanks Hannes!

**Comment by hannesdelbeke** [comment]
glad to hear that,
if you find figmapy usefull consider giving the repo a star ;)
